main: "lg.Core"
name: "TPUChat"
version: "0.0.1-SNAPSHOT"
commands:
  reloadplayerstab:
    description: Reload Tabs Nickname
    permission: TPUChat.ReloadTabCommand
    usage: "Usage: /<command>"
  global:
    description: Send to Global Chat
    permission: TPUChat.GlobalChat
    usage: "Usage: /<command>"
    aliases:
      - g
  staffchat:
    description: Send to Staff Chat
    permission: TPUChat.StaffChat
    usage: "Usage: /<command>"
    aliases:
      - s
  tell:
    description: Send to Direct Player
    permission: TPUChat.TellChat
    usage: "Usage: /<command>"
    aliases:
      - t
permissions:
  TPUChat.ReloadTabCommand:
    default: op
  TPUChat.GlobalChat:
    default: true
  TPUChat.TellChat:
    default: true
  TPUChat.StaffChat:
    default: op